kind: pipeline
type: kubernetes
name: publish stage-ui docs

steps:
- name: build and push
  image: plugins/docker
  settings:
    dockerfile: kube/Dockerfile
    username: json_key
    password:
      from_secret: YC_REGISTRY_KEY
    registry: cr.yandex
    repo: crptshuuct3ne1mn7rg1/stageui-docs
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi