kind: pipeline
type: kubernetes
name: publish stage-ui docs

steps:
- name: greeting
  image: docker
  commands:
  - docker build . -f ./kube/Dockerfile -t cr.yandex/crptshuuct3ne1mn7rg1/stageui-docs:v0.2.1-beta