kind: pipeline
type: exec
name: Build
trigger:
  event:
    include:
      - custom
      - tag
steps:
- name: Build
  commands:
  - kube/build.sh stageui
- name: Uploading
  depends_on:
    - "Build"
  environment:
    DOCKER_KEY:
      from_secret: DOCKER_KEY
  commands:  
  - kube/upload.sh stageui
- name: Deploy
  depends_on:
    - "Uploading"
  environment:
    KUBE_CONFIG:
      from_secret: KUBE_CONFIG
  commands:
  - kube/deploy.sh