apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs
  namespace: _NAMESPACE
  labels:
    app: docs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docs
  template:
    metadata:
      labels:
        app: docs
    spec:
      containers:
      - name: docs
        image: cr.yandex/crptshuuct3ne1mn7rg1/stageui-docs:_VERSION
        ports:
        - containerPort: 80